apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}-role
rules:
- apiGroups: [""]
  verbs: ["get", "list", "watch", "update", "create", "delete", "patch"]
  resources: ["secrets"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-sa
  namespace: {{ .Values.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}-role-binding
roleRef:
  kind: ClusterRole
  name: {{ .Values.name }}-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}-sa
    namespace: {{ .Values.namespace }}