name: Release Charts

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Configure Git
        run: |
          git config user.name "GeunjeLEE"
          git config user.email "nigasa12@gmail.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: helm
        env:
          CR_TOKEN: "${{ secrets.PAT_TOKEN }}"
          CR_OWNER: ${{ github.repository_owner }}
          CR_GIT_REPO: helm_charts
