name: Release Charts

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "GeunjeLEE"
          git config user.email "nigasa12@gmail.com"

      - name: Install chart-releaser
        run: |
          cd /tmp/
          git clone https://github.com/helm/chart-releaser
          cd chart-releaser
          go mod download
          go install ./...

      - name: Run chart-releaser
        run: |
          cr upload --owner ${{ github.repository_owner }} --git-repo helm_charts --package-path helm --token ${{ secrets.PAT_TOKEN }}
