name: Release Charts

on:
  workflow_dispatch:
  
env:
  GIT_REPO: helm_charts

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Configure Git
        run: |
          git config user.name "GeunjeLEE"
          git config user.email "nigasa12@gmail.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        
      - name: Install chart-releaser
        run: |
          curl -sSLo cr.tar.gz "https://github.com/helm/chart-releaser/releases/download/v1.2.1/chart-releaser_1.2.1_linux_amd64.tar.gz"
          tar -xzf cr.tar.gz
          rm -f cr.tar.gz
          
      - name: Package and puload helm chart
        run : |
          helm package helm --destination .deploy
          helm repo index --url https://github.co/${{ github.repository_owner }}/${{ env.GIT_REPO }}
          ./cr upload --owner ${{ github.repository_owner }} --git-repo ${{ env.GIT_REPO }} --package-path .deploy --token ${{ secrets.PAT_TOKEN }}
          ./cr index -i ./index.yaml -p .deploy/ -o ${{ github.repository_owner }} -r helm_charts  --token ${{ secrets.PAT_TOKEN }}

